FROM nginx

MAINTAINER Alan McCosh

COPY nginx.conf.default /etc/nginx/nginx.conf

COPY nginx.conf.default /etc/nginx/nginx.conf.default
COPY nginx.conf.web1only /etc/nginx/nginx.conf.web1only
COPY nginx.conf.web2only /etc/nginx/nginx.conf.web2only
